openapi: "3.0.1"
info:
  title: "lab3-francisco"
  description: "serverless academy"
  version: "2020-08-18T18:55:48Z"
servers:
- url: "https://uy8ysu8vq3.execute-api.us-west-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/test"
paths:
  /books:
    get:
      parameters:
      - name: "categoria"
        in: "query"
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/book"
        required: true
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    options:
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /books/{id}:
    get:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    put:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/book"
        required: true
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
    delete:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
    book:
      title: "Create new book"
      required:
      - "autor"
      - "año"
      - "categoria"
      - "nombre"
      type: "object"
      properties:
        nombre:
          type: "string"
        autor:
          type: "string"
        año:
          type: "number"
        categoria:
          type: "string"
